spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:media_tracker}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1221221}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:1221221}
      timeout: 2s

logging:
  level:
    org.hibernate.SQL: debug